syntax = "proto3";

package verifier;

option go_package = "github.com/salrashid123/go_tpm_registrar/verifier";

// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_opt=require_unimplemented_servers=false  --descriptor_set_out=verifier/verifier.proto.pb --go-grpc_out=. --go-grpc_opt=paths=source_relative verifier/verifier.proto

service Verifier {
  rpc OfferEK (OfferEKRequest) returns (OfferEKResponse) { }
  rpc OfferAK (OfferAKRequest) returns (OfferAKResponse) { }      
  rpc GetMakeCredential (GetMakeCredentialRequest) returns (GetMakeCredentialResponse) { }
  rpc SetActivateCredential (SetActivateCredentialRequest) returns (SetActivateCredentialResponse) { }  
  rpc OfferQuote (OfferQuoteRequest) returns (OfferQuoteResponse) { }
  rpc SetQuote (SetQuoteRequest) returns (SetQuoteResponse) { }   
}

message OfferEKRequest {
  bytes ekCert = 1;  
}

message OfferEKResponse {}

message OfferAKRequest {
  bytes attestation_parameters = 1;  
  bytes ak_csr = 2;  
}

message OfferAKResponse {}

message GetMakeCredentialRequest {}

message GetMakeCredentialResponse {
    bytes encrypted_credentials = 1;  
}

message SetActivateCredentialRequest {
  bytes secret = 1;  
}

message SetActivateCredentialResponse {}

message OfferQuoteRequest {}

message OfferQuoteResponse {
  bytes nonce = 1;
}

message SetQuoteRequest {
  bytes platform_attestation = 1;
}

message SetQuoteResponse {
  bytes ak_certificate = 1;
}
